// Generates src/environments/environment.development.ts from .env before serve/build.
// Browsers can't read process.env, so real values must be inlined at generation time.
require('dotenv').config();
const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.SUPABASE_URL || 'https://YOUR_PROJECT.supabase.co';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

const content = `// Auto-generated by scripts/set-env.js from .env - do not edit directly.
// Local dev backend. Requests go through the ng serve proxy (see proxy.conf.json)
// so the browser never makes a cross-origin call and CORS never comes into play.
// Point proxy.conf.json's target at whichever host you're testing against.
export const environment = {
    production: false,
    apiBaseUrl: '',
    supabaseUrl: '${supabaseUrl}',
    supabaseAnonKey: '${supabaseAnonKey}',
};
`;

const outPath = path.join(__dirname, '../src/environments/environment.development.ts');
fs.writeFileSync(outPath, content);
console.log(`Wrote ${path.relative(process.cwd(), outPath)}`);
